FROM node:16-alpine

WORKDIR /user-app

COPY package*.json ./

RUN npm ci

COPY --chown=1001:0 . .
RUN chmod -R g=u .
RUN mkdir /.npm
RUN chown -R 1001:0 /.npm

ARG ENV=production
ENV NODE_ENV $ENV

USER 1001
CMD npm run $NODE_ENV